# Generated by Django 2.2.3 on 2019-07-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='url_name',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
