# Generated by Django 2.1 on 2020-01-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tool_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMCCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('cust_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GMCTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffd_id', models.IntegerField()),
                ('ffd_name', models.CharField(max_length=100)),
                ('wfd_input_type', models.CharField(max_length=50)),
                ('wfd_input_name', models.CharField(max_length=50)),
                ('wfd_name', models.CharField(max_length=50)),
                ('wfd_multiple_records', models.BooleanField()),
                ('wfd_delimiter', models.CharField(max_length=2)),
                ('wfd_text_qualifier', models.CharField(max_length=2)),
                ('wfd_props', models.TextField()),
                ('gmccustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GMCCustomer')),
            ],
        ),
    ]
