# Generated by Django 2.1.13 on 2020-06-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gmccustomer_gmctemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRDAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_answer', models.CharField(max_length=100)),
                ('csr_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BRDCSRMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csr_tab', models.CharField(max_length=20)),
                ('csr_setting', models.CharField(max_length=50)),
                ('table_ref', models.CharField(max_length=100)),
                ('col_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BRDLoadAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BRDLoadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveygizmo_id', models.IntegerField()),
                ('survey_answer', models.CharField(max_length=100)),
                ('csr_setting', models.CharField(max_length=100)),
                ('csr_value', models.CharField(max_length=100)),
                ('mapped', models.BooleanField()),
                ('load_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BRDLoadAttempts')),
            ],
        ),
        migrations.CreateModel(
            name='BRDQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveygizmo_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='brdcsrmappings',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BRDQuestions'),
        ),
        migrations.AddField(
            model_name='brdanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BRDQuestions'),
        ),
    ]
