# Generated by Django 2.1.13 on 2020-06-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200602_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('owner', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('language', models.CharField(max_length=3)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='app.Collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='brdanswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='brdcsrmappings',
            name='question',
        ),
        migrations.RemoveField(
            model_name='brdloadinfo',
            name='load_attempt',
        ),
        migrations.DeleteModel(
            name='BRDAnswers',
        ),
        migrations.DeleteModel(
            name='BRDCSRMappings',
        ),
        migrations.DeleteModel(
            name='BRDLoadAttempts',
        ),
        migrations.DeleteModel(
            name='BRDLoadInfo',
        ),
        migrations.DeleteModel(
            name='BRDQuestions',
        ),
    ]
