# Generated by Django 2.1.13 on 2020-06-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200603_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_answer', models.CharField(max_length=100)),
                ('csr_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BRDQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveygizmo_id', models.IntegerField()),
                ('question', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectiontitle',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionTitle',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='app.BRDQuestions'),
        ),
    ]
