# Generated by Django 2.1.13 on 2020-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200603_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question',
            new_name='ans_parent',
        ),
        migrations.AlterField(
            model_name='brdquestions',
            name='surveygizmo_id',
            field=models.CharField(max_length=10),
        ),
    ]
