# Generated by Django 2.1.13 on 2020-06-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200603_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRDLoadAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BRDLoadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveygizmo_id', models.IntegerField()),
                ('survey_answer', models.CharField(max_length=100)),
                ('csr_setting', models.CharField(max_length=100)),
                ('csr_value', models.CharField(max_length=100)),
                ('mapped', models.BooleanField()),
                ('load_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_attempts', to='app.BRDLoadAttempts')),
            ],
        ),
    ]
