# Generated by Django 2.1.13 on 2020-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brdloadattempts_brdloadinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brdloadinfo',
            name='col_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='brdloadinfo',
            name='csr_tab',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='brdloadinfo',
            name='table_ref',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='csr_setting',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='csr_value',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
