# Generated by Django 2.1.13 on 2020-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200616_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brdloadattempts',
            name='status',
            field=models.CharField(default='partial', max_length=10),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='col_name',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='csr_setting',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='csr_tab',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='csr_value',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='brdloadinfo',
            name='table_ref',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='csrmappings',
            name='col_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='csrmappings',
            name='csr_setting',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='csrmappings',
            name='csr_tab',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='csrmappings',
            name='table_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
