# Generated by Django 2.1.13 on 2020-06-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200629_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='brdloadattempts',
            name='pcase_num',
            field=models.IntegerField(blank=True, default=12345),
        ),
        migrations.AddField(
            model_name='brdloadattempts',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='brdquestions',
            name='survey_id',
            field=models.CharField(default='4623162', max_length=10),
        ),
        migrations.AlterField(
            model_name='brdloadattempts',
            name='customer_id',
            field=models.IntegerField(blank=True, default=12345),
        ),
        migrations.AlterField(
            model_name='brdloadattempts',
            name='response_id',
            field=models.IntegerField(blank=True, default=12345),
        ),
        migrations.AlterField(
            model_name='brdloadattempts',
            name='survey_id',
            field=models.CharField(choices=[('4623162', 'BRD'), ('5671111', 'New BRD')], default='BRD', max_length=10),
        ),
    ]
