# Generated by Django 2.1.13 on 2020-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200630_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCustomerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ref', models.CharField(blank=True, max_length=100)),
                ('cust_id_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
