# Generated by Django 2.1.13 on 2020-07-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tablecustomerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brdloadinfo',
            name='load_attempt',
        ),
        migrations.DeleteModel(
            name='BRDLoadInfo',
        ),
    ]
