# Generated by Django 2.1.13 on 2020-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200721_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brdloadattempts',
            name='pcase_num',
            field=models.CharField(default='PLEASE FILL IN', max_length=20),
        ),
    ]
